# Monitor setup
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
# xrandr --listactivemonitors | awk '{ print $4 }' | sort | tr '\n' ' ' | read eDP HDMI # monitor names change occasionally
# xrandr --output $eDP --below $HDMI --primary
python connect_monitors.py
xset -dpms
xset s off

# Appearances
xrdb ~/.Xresources
xbanish &
picom &
feh --no-fehbg --bg-scale ~/media/images/backgrounds/abstract-cubes.jpg &
xsetroot -cursor_name left_ptr &
# redshift &

# Default programs
# xset r rate 160 20 &
xmodmap -e "keycode 108 = Multi_key" # for XCompose
/usr/bin/qutebrowser --restore default &
/usr/bin/firefox-developer-edition &
$HOME/.local/kitty.app/bin/kitty &
/home/trey/dev/scripts/super-caps.sh &
/usr/lib/notification-daemon-1.0/notification-daemon &

# Launch XMonad (the best WM)
$HOME/.xmonad/xmonad-x86_64-linux # >| ~/.local/share/log 2>&1
