#!/bin/sh
# vim: filetype=zsh.vim

#
# Monitor setup
#
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
# xinitrc can't read variables...
# xrandr --listactivemonitors | awk '{ print $4 }' | sort | tr '\n' ' ' | read eDP HDMI
# xrandr --output $eDP --below $HDMI --primary
connect_monitors.py

# ~/.local/bin/scripts/connect_monitors.py # for some reason this works and not the equivalent bash script
xset -dpms # don't screen blank
xset s off

#
# Appearances
#
xrdb ~/.Xresources &
xbanish &
~/dev/jonaburg/picom/build/src/picom --experimental-backends --config ~/.config/picom/picom-jonaburg.conf &
xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-fill '/home/trey/media/backgrounds/firewatch.jpg' '/home/trey/media/backgrounds/xiaomi-mi-gaming-laptop-abstract-4k-hl-2560x1440.jpg' &
# xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID ~/media/backgrounds/videos/DVDE_loop.mp4 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings &
# ~/bin/back4.sh auto ~/media/gif/beautycity.gif &

#
# Default programs
#
# xset r rate 160 20 &
# pacmd set-default-source $(pacmd list-sources | grep name: | grep input | sed 's/^.*<\(.*\)>/\1/p')
mkdir /tmp/$USER/
xmodmap -e "keycode 108 = Multi_key" # for XCompose
browser-profiles personal &
browser-profiles work &
browser-profiles misc &
kitty &
super-caps.sh &
/usr/lib/notification-daemon-1.0/notification-daemon &

#
# Launch XMonad (the best WM)
#
$HOME/.xmonad/xmonad-x86_64-linux # >| ~/.local/share/log 2>&1
